language: php

php:
    - 5.5
    - 5.6

before_script:
    - composer self-update
    - travis_retry composer install

script:
    - make cs
    - make tests

notifications:
    email: false
    irc:
        skip_join: true
        use_notice: true
        channels:
            - "irc.freenode.org#cotapreco"
        template:
            - "%{repository} (%{commit} - %{author}), %{build_url} — %{result}"
